FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY backend/go-api/go.mod ./
COPY backend/go-api/main.go ./
RUN go build -o api main.go

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/api ./api
EXPOSE 8080
CMD ["./api"]
