global:
  scrape_interval: 15s

scrape_configs:
  - job_name: aws-retailops-backend
    static_configs:
      - targets: ["backend:8080"]
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
